# Changes here will be overwritten by Copier
_commit: cbb6305
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: timkpaine
project_description: Engage with Zorp!
project_name: organizeit2
python_version_primary: '3.11'
team: the organizeit2 authors
