# Changes here will be overwritten by Copier
_commit: 37f89c1
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: rust
add_wiki: false
email: t.paine154@gmail.com
github: 1kbgz
project_description: Engage with Zorp!
project_name: organizeit2
python_version_primary: '3.11'
team: the organizeit2 authors
